// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Footer() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<footer><section class=\"flex items-center justify-center gap-4 text-gray-200 p-1 text-sm bg-zinc-900 md:p-4\" hx-boost=\"true\"><a href=\"/about\">About</a> <a href=\"/contact\">Contact</a> <a href=\"/terms\">Terms</a> <a href=\"/privacy\">Privacy</a> <a href=\"/cookies\">Cookies</a> <a href=\"/admin\">Admin</a></section><section class=\"flex items-center\n    justify-center gap-4 bg-zinc-950 p-1\n    text-center text-sm text-white\n    md:p-4\"><span>Powered by <a href=\"https://github.com/go-fuego/fuego\" class=\"\n        inline-block\n        bg-linear-to-r from-orange-300 to-orange-500\n        bg-clip-text font-bold italic text-transparent\">Fuego</a></span> 🔥</section></footer>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
