// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Scripts() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<script defer type=\"text/javascript\" src=\"https://cdn.jsdelivr.net/npm/toastify-js\"></script><script defer src=\"https://unpkg.com/htmx.org/dist/htmx.min.js\">\n  htmx.on(\"htmx:sendError\", function (evt) {\n    errormessage_on();\n  });\n\n  function errormessage_on() {\n    const errDiv = document.getElementById(\"errormessages\");\n    errDiv.classList.remove(\"hidden\");\n    errDiv.classList.add(\"flex\");\n  }\n\n  function errormessage_off() {\n    const errDiv = document.getElementById(\"errormessages\");\n    errDiv.classList.add(\"hidden\");\n    errDiv.classList.remove(\"flex\");\n  }\n\n  document.body.addEventListener(\"entity-updated\", function(evt) {\n    Toastify({\n      text: \"Updated successfully\",\n      duration: 3000,\n      close: true,\n      stopOnFocus: true, // Prevents dismissing of toast on hover\n      style: {\n        background: \"linear-gradient(to right, #00b09b, #96c93d)\",\n      },\n    }).showToast();\n  })\n\n</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
