version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/documentation"
      - "/examples/**/*"
    groups:
      all:
        patterns:
          - "*"  # Group all updates into a single larger pull request.
    open-pull-requests-limit: 10  # avoid spam, if no one reacts
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directories: 
      - /
      - /cmd/**/*
      - /examples/**/*
      - /extra/**/*
    groups:
      all:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"

  - package-ecosystem: github-actions
    directory: /
    groups:
      all:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    schedule:
      interval: weekly
    
