run:
  go: "1.22"
  timeout: 1m
  tests: false

linters:
  disable-all: false
  enable:
    - errcheck
    - gci
    - gofumpt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
    - usestdlibvars
    - whitespace

linters-settings:
  misspell:
    locale: "US"
    error: true

  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment

  gofumpt:
    extra-rules: true
  staticcheck:
    checks: ["all"]
  gci:
    sections:
      # Standard section: captures all standard packages.
      - standard
      # Default section: catchall that is not standard or custom
      - default
      # linters that related to fuego, so they should be separated
      - localmodule
