run:
  go: "1.22"
  timeout: 1m
  tests: false

issues:
  include:
    - "EXC0014" # Enable revive export rule with "should start with"

linters:
  disable-all: false
  enable:
    - errcheck
    - gci
    - gofumpt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
    - usestdlibvars
    - whitespace
    - revive

linters-settings:
  revive:
     rules:
      - name: exported
        arguments: ["checkPrivateReceivers", "sayRepetitiveInsteadOfStutters"]
      - name: receiver-naming
      - name: redefines-builtin-id
      # These ones are usually enabled by default
      # but enabling them would require some work and further checks
      # name: unused-parameter

  misspell:
    locale: "US"
    error: true

  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment

  gofumpt:
    extra-rules: true
  staticcheck:
    checks: ["all"]
  gci:
    sections:
      # Standard section: captures all standard packages.
      - standard
      # Default section: catchall that is not standard or custom
      - default
      # linters that related to fuego, so they should be separated
      - localmodule
