run:
  go: "1.23"
  timeout: 1m
  tests: true

issues:
  include:
    - "EXC0014" # Enable revive export rule with "should start with"
  exclude-rules:
    # Exclude other linters by default on tests files
    # we only run testifylint https://github.com/Antonboom/testifylint on test files
    - path: _test\.go$
      linters:
        - errcheck
        - gci
        - gofumpt
        - gosec
        - gosimple
        - govet
        - ineffassign
        - misspell
        - staticcheck
        - unused
        - usestdlibvars
        - whitespace
        - revive
        - gocritic

linters:
  disable-all: false
  enable:
    - errcheck
    - gci
    - gocritic
    - gofumpt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - testifylint
    - unconvert
    - unused
    - usestdlibvars
    - whitespace

linters-settings:
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
        arguments: ["allowTypesBefore": "*testing.T"]
      - name: context-keys-type
      - name: dot-imports
      - name: empty-block
      - name: error-naming
      - name: error-return
      - name: error-strings
      - name: errorf
      - name: exported
        arguments: ["checkPrivateReceivers", "sayRepetitiveInsteadOfStutters"]
      - name: increment-decrement
      - name: indent-error-flow
      - name: range
      - name: receiver-naming
      - name: redefines-builtin-id
      - name: superfluous-else
      - name: time-naming
      - name: unreachable-code
      - name: var-declaration
      # These ones are usually enabled by default
      # but enabling them would require some work and further checks
      # - name: unexported-return
      # - name: unused-parameter
      # - name: var-naming

  gocritic:
    enable-all: true
    disabled-checks:
      - appendAssign    # this one is enabled by default usually, but it reports something that needs to be checked
      - hugeParam       # this one could be considered later
      - rangeValCopy    # this one should be considered later, but it requires some checks
      - regexpSimplify  # this one should be considered later, but it requires some checks

  misspell:
    locale: "US"

  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment

  gofumpt:
    extra-rules: true
  staticcheck:
    checks: ["all"]
  gci:
    sections:
      # Standard section: captures all standard packages.
      - standard
      # Default section: catchall that is not standard or custom
      - default
      # linters that related to fuego, so they should be separated
      - localmodule

  testifylint:
    enable-all: true
