[default]
extend-words = { "SerDes" = "SerDes" }
locale = "en-us"

[files]
# excluded file
extend-exclude = [
   "go.sum", "go.mod", # these files are specific to Go, they shouldn't get parsed for typos
]
