[default]
locale = "en-us"

[default.extend-words]
# Don't correct the surname "ser"
ser = "ser"

[files]
# excluded file
extend-exclude = [
   "go.sum", "go.mod", # these files are specific to Go, they shouldn't get parsed for typos
]
