// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package store

import (
	"time"
)

type Dosing struct {
	RecipeID     string `json:"recipe_id"`
	IngredientID string `json:"ingredient_id"`
	Quantity     int64  `json:"quantity" validate:"required,gt=0"`
	Unit         string `json:"unit" validate:"required"`
}

type Ingredient struct {
	ID          string    `json:"id"`
	CreatedAt   time.Time `json:"created_at"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	DefaultUnit string    `json:"default_unit"`
}

type Recipe struct {
	ID           string    `json:"id"`
	CreatedAt    time.Time `json:"created_at"`
	Name         string    `json:"name"`
	Description  string    `json:"description"`
	Instructions string    `json:"instructions"`
}
