// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: recipe.sql

package store

import (
	"context"
	"database/sql"
)

const createRecipe = `-- name: CreateRecipe :one
INSERT INTO recipe (id, name, description, instructions) VALUES (?, ?, ?, ?) RETURNING id, created_at, name, description, instructions, category, class, published, created_by, calories, cost, prep_time, cook_time, servings, image_url, disclaimer
`

type CreateRecipeParams struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	Description  string `json:"description"`
	Instructions string `json:"instructions"`
}

func (q *Queries) CreateRecipe(ctx context.Context, arg CreateRecipeParams) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, createRecipe,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Instructions,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Name,
		&i.Description,
		&i.Instructions,
		&i.Category,
		&i.Class,
		&i.Published,
		&i.CreatedBy,
		&i.Calories,
		&i.Cost,
		&i.PrepTime,
		&i.CookTime,
		&i.Servings,
		&i.ImageUrl,
		&i.Disclaimer,
	)
	return i, err
}

const deleteRecipe = `-- name: DeleteRecipe :exec
DELETE FROM recipe WHERE id = ?
`

func (q *Queries) DeleteRecipe(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRecipe, id)
	return err
}

const getRandomRecipes = `-- name: GetRandomRecipes :many
SELECT id, created_at, name, description, instructions, category, class, published, created_by, calories, cost, prep_time, cook_time, servings, image_url, disclaimer FROM recipe ORDER BY RANDOM() DESC LIMIT 10
`

func (q *Queries) GetRandomRecipes(ctx context.Context) ([]Recipe, error) {
	rows, err := q.db.QueryContext(ctx, getRandomRecipes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipe
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Name,
			&i.Description,
			&i.Instructions,
			&i.Category,
			&i.Class,
			&i.Published,
			&i.CreatedBy,
			&i.Calories,
			&i.Cost,
			&i.PrepTime,
			&i.CookTime,
			&i.Servings,
			&i.ImageUrl,
			&i.Disclaimer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecipe = `-- name: GetRecipe :one
SELECT id, created_at, name, description, instructions, category, class, published, created_by, calories, cost, prep_time, cook_time, servings, image_url, disclaimer FROM recipe WHERE id = ?
`

func (q *Queries) GetRecipe(ctx context.Context, id string) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, getRecipe, id)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Name,
		&i.Description,
		&i.Instructions,
		&i.Category,
		&i.Class,
		&i.Published,
		&i.CreatedBy,
		&i.Calories,
		&i.Cost,
		&i.PrepTime,
		&i.CookTime,
		&i.Servings,
		&i.ImageUrl,
		&i.Disclaimer,
	)
	return i, err
}

const getRecipes = `-- name: GetRecipes :many
SELECT id, created_at, name, description, instructions, category, class, published, created_by, calories, cost, prep_time, cook_time, servings, image_url, disclaimer FROM recipe
`

func (q *Queries) GetRecipes(ctx context.Context) ([]Recipe, error) {
	rows, err := q.db.QueryContext(ctx, getRecipes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipe
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Name,
			&i.Description,
			&i.Instructions,
			&i.Category,
			&i.Class,
			&i.Published,
			&i.CreatedBy,
			&i.Calories,
			&i.Cost,
			&i.PrepTime,
			&i.CookTime,
			&i.Servings,
			&i.ImageUrl,
			&i.Disclaimer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchRecipes = `-- name: SearchRecipes :many
SELECT id, created_at, name, description, instructions, category, class, published, created_by, calories, cost, prep_time, cook_time, servings, image_url, disclaimer FROM recipe WHERE name LIKE ?
`

// Saerch anything that contains the given string
func (q *Queries) SearchRecipes(ctx context.Context, name string) ([]Recipe, error) {
	rows, err := q.db.QueryContext(ctx, searchRecipes, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipe
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Name,
			&i.Description,
			&i.Instructions,
			&i.Category,
			&i.Class,
			&i.Published,
			&i.CreatedBy,
			&i.Calories,
			&i.Cost,
			&i.PrepTime,
			&i.CookTime,
			&i.Servings,
			&i.ImageUrl,
			&i.Disclaimer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecipe = `-- name: UpdateRecipe :one
UPDATE recipe SET 
  name=COALESCE(?1, name),
  description=COALESCE(?2, description),
  instructions=COALESCE(?3, instructions),
  category=COALESCE(?4, category),
  class=COALESCE(?5, class),
  image_url=COALESCE(?6, image_url),
  cook_time=COALESCE(?7, cook_time),
  prep_time=COALESCE(?8, prep_time),
  servings=COALESCE(?9, servings),
  published=COALESCE(?10, published)
WHERE id = ?11
RETURNING id, created_at, name, description, instructions, category, class, published, created_by, calories, cost, prep_time, cook_time, servings, image_url, disclaimer
`

type UpdateRecipeParams struct {
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	Instructions sql.NullString `json:"instructions"`
	Category     string         `json:"category"`
	Class        string         `json:"class"`
	ImageUrl     string         `json:"image_url"`
	CookTime     int64          `json:"cook_time"`
	PrepTime     int64          `json:"prep_time"`
	Servings     int64          `json:"servings"`
	Published    bool           `json:"published"`
	ID           string         `json:"id"`
}

func (q *Queries) UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, updateRecipe,
		arg.Name,
		arg.Description,
		arg.Instructions,
		arg.Category,
		arg.Class,
		arg.ImageUrl,
		arg.CookTime,
		arg.PrepTime,
		arg.Servings,
		arg.Published,
		arg.ID,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Name,
		&i.Description,
		&i.Instructions,
		&i.Category,
		&i.Class,
		&i.Published,
		&i.CreatedBy,
		&i.Calories,
		&i.Cost,
		&i.PrepTime,
		&i.CookTime,
		&i.Servings,
		&i.ImageUrl,
		&i.Disclaimer,
	)
	return i, err
}
