// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package admin

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func AdminNavbar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<nav class=\"w-full md:w-64 space-y-6 bg-zinc-900 p-4 md:py-8 text-gray-400 shadow-sm\" hx-boost=\"true\" hx-target=\"#page\" hx-select=\"#page\" hx-swap=\"outerHTML\"><h1 class=\"mb-4 text-center\"><a class=\"inline-block bg-linear-to-r\n\t\t\t\t\t\t\t\tfrom-orange-300\n\t\t\t\t\t\t\t\tto-orange-500 bg-clip-text font-serif\n\t\t\t\t\t\t\t\ttext-2xl font-bold italic text-transparent\" href=\"/\" hx-boost=\"false\">Gourmet</a></h1><ul><li class=\"mb-4 text-xl text-white hover:text-gray-200 hover:underline\"><a href=\"/admin/recipes\">Recipes</a></li><li class=\"mb-4 text-xl text-white hover:text-gray-200 hover:underline\"><a href=\"/admin/ingredients\">Ingredients</a></li><li class=\"mb-4 text-xl text-white hover:text-gray-200 hover:underline\"><a href=\"/admin/users\">Users</a></li></ul></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
