name: Release Please

on:
  push:
    branches: [ main ]

jobs:
  track-release:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.track-release.outputs.release_created }}
    steps:
      - uses:
          googleapis/release-please-action@v4
        id: track-release
        with:
          manifest-file: .github/.release-please-manifest.json
          config-file: .github/release-please-config.json
  goreleaser:
    needs:
      - track-release
    if: ${{ needs.track-release.outputs.release_created }}

    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

